blueprint:
  name: Lightning control
  description: >-
    Switch a light on/off by pressing a button.
    Double press to toggle the light on max.
    Dim it up/down (depending on it's current state) by holding the same button.
  domain: automation
  input:
    triggers:
      name: "Triggers *"
      icon: mdi:cog-outline
      collapsed: true
      input:
        trigger:
          name: Trigger Sensor - Binary Sensors - Schedule *
          description: The trigger sensors are responsible for turning the lights, switches, scenes, and scripts ON and OFF. You can choose any [binary sensors](https://www.home-assistant.io/integrations/binary_sensor/) you prefer as triggers.
            Alternatively, if you prefer a time-based trigger, you can also add a [schedule helper](https://community.home-assistant.io/t/481048/1616).
            
            
            When using multiple trigger sensors, it's advisable to group them together using a group helper.
            This ensures smoother automation execution and prevents conflicts.
            
            
            For more information on grouping your trigger sensors [Click Here](https://community.home-assistant.io/t/481048/34)
          default: []
          selector:
            entity:
              filter:
                domain:
                  - binary_sensor
                  - schedule
              multiple: true

mode: single

trigger:
  - platform: state
    entity_id: !input trigger
    to: "on"

action:
  - variables:
      brightness_step_pct_positive: !input brightness_step_pct
  - variables:
      brightness_step_pct_negative: "{{ brightness_step_pct_positive|int * -1 }}"
      light: !input light
  - wait_for_trigger:
      - platform: state
        entity_id: !input button
        to: "off"
        from: "on"
    timeout: !input hold_threshold
    continue_on_timeout: true
  - choose:
      - conditions:
          # when no trigger came (button has not been switched back to
          # off state during timeout) = button is being held
          - condition: template
            value_template: "{{ wait.trigger == none }}"
        sequence:
          - choose:
              - conditions:
                  # when brightness level is high
                  - condition: numeric_state
                    entity_id: !input light
                    attribute: brightness
                    above: !input brightness_threshold
                sequence:
                  # dim down
                  - repeat:
                      while:
                        - condition: and
                          conditions:
                            - condition: state
                              entity_id: !input button
                              state: "on"
                            - condition: template
                              value_template: "{{ (state_attr(light, 'brightness') or 0) > 0 }}"
                      sequence:
                        - if:
                            - alias: If next step would not turn off the light
                              condition: template
                              value_template: "{{ (state_attr(light, 'brightness') or 0) > brightness_step_pct_positive }}"
                          then:
                            - service: light.turn_on
                              entity_id: !input light
                              data:
                                transition: !input transition_step_length
                                brightness_step_pct: "{{ brightness_step_pct_negative }}"
                          else:
                            - service: light.turn_off
                              entity_id: !input light
                              data:
                                transition: !input transition_step_length
                            - stop: Dimmed to zero
                        - delay: !input delay_step_length
            default:
              # otherwise, dim up
              - repeat:
                  while:
                    - condition: and
                      conditions:
                        - condition: state
                          entity_id: !input button
                          state: "on"
                        - condition: template
                          value_template: "{{ (state_attr(light, 'brightness') or 0) < 255 }}"
                  sequence:
                    - if:
                        - alias: If next step would not turn the light fully on
                          condition: template
                          value_template: "{{ (state_attr(light, 'brightness') or 0) + brightness_step_pct_positive < 255 }}"
                      then:
                        - service: light.turn_on
                          entity_id: !input light
                          data:
                            transition: !input transition_step_length
                            brightness_step_pct: "{{ brightness_step_pct_positive }}"
                      else:
                        - service: light.turn_on
                          entity_id: !input light
                          data:
                            transition: !input transition_step_length
                        - stop: Dimmed to max
                    - delay: !input delay_step_length

    # when trigger came (button has been released within timeout)
    default:
      - service: light.toggle
        entity_id: !input light
        data:
          transition: !input transition_step_length