blueprint:
  name: Lightning control
  description: >-
    Switch a light on/off by pressing a button.
    Double press to toggle the light on max.
    Dim it up/down (depending on it's current state) by holding the same button.
  domain: automation
  input:
    triggers:
      name: "Triggers *"
      icon: mdi:cog-outline
      collapsed: true
      input:
        trigger:
          name: Trigger Sensor - Binary Sensors - Schedule *
          description: The trigger sensors are responsible for turning the lights, switches, scenes, and scripts ON and OFF. You can choose any [binary sensors](https://www.home-assistant.io/integrations/binary_sensor/) you prefer as triggers.
            Alternatively, if you prefer a time-based trigger, you can also add a [schedule helper](https://community.home-assistant.io/t/481048/1616).
          default: []
          selector:
            entity:
              filter:
                domain:
                  - binary_sensor
                  - schedule
              multiple: true
        boolean_dimmer:
          name: Dimmer
          description: Is the trigger ...
          default: []
          selector:
            entity:
              filter:
                domain:
                  - input_boolean

mode: single

trigger:
  - platform: state
    entity_id: !input trigger
    to: "on"
